name: LLM | Build → Push(Docker Hub) → (artifact) → Notify infra

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  SERVICE: llm
  IMAGE_NAME: carnav-llm
  DOCKERHUB_NAMESPACE: gabicate
  INFRA_REPO: gabriella0128/career-navigator-infra

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set TAG
        id: meta
        run: echo "TAG=main-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # env 조합은 env 블록에서 못 하므로, 런타임에 FULL_IMAGE를 주입
      - name: Compose FULL_IMAGE
        run: echo "FULL_IMAGE=docker.io/${DOCKERHUB_NAMESPACE}/${IMAGE_NAME}" >> "$GITHUB_ENV"

      # PR에서는 도커 허브 푸시 안 하고, 빌드만 체크(선택)
      - name: Build (no push) on PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false

      # master push 에서만 로그인 + 푸시 + 아티팩트 + 통지
      - name: Login to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.FULL_IMAGE }}:v1
            ${{ env.FULL_IMAGE }}:${{ steps.meta.outputs.TAG }}

      - name: Notify infra (repository_dispatch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peter-evans/repository-dispatch@v3
        with:
          token:      ${{ secrets.INFRA_REPO_TOKEN }}
          repository: ${{ env.INFRA_REPO }}
          event-type: deploy
          client-payload: |
            {
              "service": "llm",
              "tag": "${{ steps.meta.outputs.TAG }}",
              "repo": "${{ github.repository }}",
              "run_id": "${{ github.run_id }}",
              "artifact_name": "llm-image-${{ steps.meta.outputs.TAG }}",
              "image_name": "${{ env.IMAGE_NAME }}",
              "full_image": "${{ env.FULL_IMAGE }}"
            }
